### ISSUE TITLE
feat: option to display at the bottom

### ISSUE THREAD

**Issue by pedro757** [Mofiqul/trld.nvim#1]
It would be cool to have the ability to change where to display the diagnotics (top or bottom)

**Comment by Mofiqul** [comment]
Yeah, can be done. I will look it into tomorrow

**Comment by cseickel** [comment]
Another variation of this that I would like is the option to display on the bottom only if displaying on the top might overlap real text in the buffer. A quick version of this would be to just switch to a bottom placement if the cursor is within x lines of the top of the window.

**Comment by Mofiqul** [comment]
@cseickel and @pedro757 - Display on bottom works, but with a con. The bottom is the last line of
the buffer which may not be the bottom of the window, If there is only a
few line in the document, it will display on the last line. In future if
I find a fix for that, I will do it.

Edit: Please see the README for setup.
