### ISSUE TITLE
Error while editing a .astro file

### ISSUE THREAD

**Issue by cjnucette** [Mofiqul/trld.nvim#5]
Hi, I am getting the following error when editing the javascript section of a .astro file.

    Error detected while processing CursorHoldI Autocommands for "*":                                                                                                                              
    E5108: Error executing lua ...cette/.config/nvim/plugged/trld.nvim/lua/trld/config.lua:23: attempt to index local 
    'code' (a number value)                                                      
    stack traceback:                                                                                                                                                                               
            ...cette/.config/nvim/plugged/trld.nvim/lua/trld/config.lua:23: in function 'formatter'                                                                                                
            ...ucette/.config/nvim/plugged/trld.nvim/lua/trld/utils.lua:45: in function 'display_diagnostics'                                                                                      
            /home/cjnucette/.config/nvim/plugged/trld.nvim/lua/trld.lua:34: in function 'TRLDShow'                                                                                                 
            [string ":lua"]:1: in main chunk

It would be nice to have an option to disable this plugin based on the filetype.
Great plugin by the way!

**Comment by Mofiqul** [comment]
This has been fixed. Please update the plugin.

**Comment by cjnucette** [comment]
Fixed!, this was fast. Thank you.
